import { ProjectsSectionType } from '@/lib/types/sections';
import { getId } from '@/lib/utils/helper';

export const projectsSection: ProjectsSectionType = {
  title: 'my projects',
  projects: [
    {
      id: getId(),
      name: 'cryptocurrency home page',
      url: 'https://github.com/shamshubham/Cryptocurrency-website-design',
      repo: 'https://github.com/shamshubham/Cryptocurrency-website-design',
      img: 'https://raw.githubusercontent.com/shamshubham/Cryptocurrency-website-design/master/screenShots/Capture.JPG',
      year: 2023,
      tags: ['React', 'Tailwind'],
    },
    {
      id: getId(),
      name: 'website coming soon webpage',
      url: 'https://github.com/shamshubham/Website-coming-soon-webpage',
      repo: 'https://github.com/shamshubham/Website-coming-soon-webpage',
      img: 'https://raw.githubusercontent.com/shamshubham/Website-coming-soon-webpage/master/screenShots/Capture.JPG',
      year: 2023,
      tags: ['NodeJs', 'Express', 'Mongoose'],
    },
    {
      id: getId(),
      name: 'pig game',
      url: 'https://github.com/shamshubham/pig-game',
      repo: 'https://github.com/shamshubham/pig-game',
      img: 'https://raw.githubusercontent.com/shamshubham/pig-game/master/screenShots/Capture.JPG',
      year: 2022,
      tags: ['HTML', 'CSS', 'JS'],
    },
    {
      id: getId(),
      name: 'guess my number',
      url: 'https://github.com/shamshubham/guess_my_number',
      repo: 'https://github.com/shamshubham/guess_my_number',
      img: 'https://raw.githubusercontent.com/shamshubham/guess_my_number/master/screenShots/Capture2.JPG',
      year: 2022,
      tags: ['HTML', 'CSS', 'JS'],
    },
    {
      id: getId(),
      name: 'digital clock',
      url: 'https://github.com/shamshubham/Digital-clock',
      repo: 'https://github.com/shamshubham/Digital-clock',
      img: 'https://raw.githubusercontent.com/shamshubham/Digital-clock/master/screenShots/Capture.JPG',
      year: 2022,
      tags: ['HTML', 'CSS', 'JS'],
    },
    {
      id: getId(),
      name: 'bankist app',
      url: 'https://github.com/shamshubham/bankist-app',
      repo: 'https://github.com/shamshubham/bankist-app',
      img: 'https://raw.githubusercontent.com/shamshubham/bankist-app/master/screenShots/Capture.JPG',
      year: 2022,
      tags: ['HTML', 'CSS', 'JS'],
    },
    {
      id: getId(),
      name: 'image search engine',
      url: 'https://github.com/shamshubham/Image-search-engine',
      repo: 'https://github.com/shamshubham/Image-search-engine',
      img: 'https://raw.githubusercontent.com/shamshubham/Image-search-engine/master/screenShots/Capture.JPG',
      year: 2022,
      tags: ['HTML', 'CSS', 'JS'],
    },
    {
      id: getId(),
      name: 'music player',
      url: 'https://github.com/shamshubham/Music-player',
      repo: 'https://github.com/shamshubham/Music-player',
      img: 'https://raw.githubusercontent.com/shamshubham/Music-player/master/screenShots/Capture.JPG',
      year: 2022,
      tags: ['HTML', 'CSS', 'JS'],
    },
    {
      id: getId(),
      name: 'to do list',
      url: 'https://github.com/shamshubham/To-Do-List',
      repo: 'https://github.com/shamshubham/To-Do-List',
      img: 'https://github.com/shamshubham/To-Do-List/blob/main/screenShots/Capture2.JPG',
      year: 2022,
      tags: ['HTML', 'CSS', 'JS'],
    },
    {
      id: getId(),
      name: 'text to speech converter',
      url: 'https://github.com/shamshubham/Text-to-speech-converter',
      repo: 'https://github.com/shamshubham/Text-to-speech-converter',
      img: 'https://raw.githubusercontent.com/shamshubham/Text-to-speech-converter/master/screenShots/Capture.JPG',
      year: 2022,
      tags: ['Html', 'CSS', 'JS'],
    },
    {
      id: getId(),
      name: 'weather app',
      url: 'https://github.com/shamshubham/weather-app',
      repo: 'https://github.com/shamshubham/weather-app',
      img: 'https://raw.githubusercontent.com/shamshubham/weather-app/main/screenShots/Capture.JPG',
      year: 2022,
      tags: ['Html', 'CSS', 'JS'],
    },
  ],
};
